platform :ios, '7.0'
pod "AFNetworking", "~> 2.0"
pod 'AFNetworkActivityLogger'

post_install do |installer_representation|
    installer_representation.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['ONLY_ACTIVE_ARCH'] = 'NO'
        end
    end
end
